-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZFEypYbh9Gdqwnh0
643YPDr4SjVaV8fWhSYN93Nf+fSgCgYIKoZIzj0DAQehRANCAAR28H8juX5OmF0m
ExILZzMcQRELvYyaH57yOKRhVMjBRrgvcHrlbG9UcPzwKVGHc2jX/+4FGRzpWfWa
eTNcUKyP
-----END PRIVATE KEY-----